[package]
name = "r_routersploit"
version = "0.1.0"
edition = "2021"

[dependencies]
# For HTTP requests
reqwest = { version = "0.12.15", features = ["json"] }

# For CLI parsing
clap = { version = "4.5.35", features = ["derive"] }

# Async runtime for networking
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"] }

# Easier error handling
anyhow = "1.0.97"

#teminal color
colored = "3.0.0"

#ftp brute force module
async_ftp = "6.0.0"

tokio-socks = "0.5.2"

