[package]
name = "rustsploit"
version = "0.1.0"
edition = "2021"

[dependencies]
# For HTTP requests
reqwest = { version = "0.12.15", features = ["json", "socks"] }

#proxy manager
rand = "0.9.0"

# For CLI parsing
clap = { version = "4.5.35", features = ["derive"] }

# Async runtime for networking
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread", "process"] }

# Easier error handling
anyhow = "1.0.97"

#teminal color
colored = "3.0.0"
rustyline = "15.0.0"
#ftp brute force module
async_ftp = "6.0.0"

tokio-socks = "0.5.2"

#telnet
threadpool = "1.8.1"
crossbeam-channel = "0.5.15"
telnet = "0.2.3"

walkdir = "2.5.0"

#ssh
ssh2 = "0.9.5"

# rstp brute forcing
base64 = "0.22.1"

# RDP brute forcing module
rdp = "0.12.8"

# ssdp moudle scanner
regex = "1.11.1"


[[bin]]
name = "rustsploit"
path = "src/main.rs"
